name: Build ISO

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Prepare pacman keyring
        run: |
          pacman-key --init
          pacman --noconfirm -Sy archlinux-keyring
      
      - name: Install ArchISO
        run: |
          pacman -Sy
          pacman --noconfirm -S git archiso

      - name: Build ISO File
        run: |
          cd ..
          mkarchiso -v holoiso -o /tmp/holoiso
          find /tmp/holoiso

      - uses: actions/upload-artifact@v2
        with:
          name: holoiso
          path: /tmp/holoiso
